run:
  allow-parallel-runners: true
  timeout: 5m
linters:
  enable:
    - gosec
    # Add golangci-lint defaults here too, to be explicit
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
