# If you change this, be sure to update .github/workflows/terraform-test.yml
services:
  nginx:
    image: nginx:1.31@sha256:abe47724e466aeab9a345d8e46a221c2fa8953c7848bb4a3bd9976a7199f8cf2
    ports:
      - 8085:80
    volumes:
      - ./tests/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis:8.10-alpine@sha256:3811787313eba226a2ef38658c6ccb91cd5e110edc89c37767de373120a0e5a0
    restart: always
    ports:
      - "6379:6379"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.14@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,kms
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
