# If you change this, be sure to update .github/workflows/terraform-test.yml
services:
  nginx:
    image: nginx:1.31@sha256:c90e4ea5905ee69515d84cd5520e11d204df06cce71a312666cebbc4b9b68267
    ports:
      - 8085:80
    volumes:
      - ./tests/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis:8.8-alpine@sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005
    restart: always
    ports:
      - "6379:6379"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.14@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,kms
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
