# If you change this, be sure to update .github/workflows/terraform-test.yml
services:
  nginx:
    image: nginx:1.31@sha256:42f2d24ae18df9b5251d1cc45548085656d2335e9338fd150a24e415462d151f
    ports:
      - 8085:80
    volumes:
      - ./tests/nginx.conf:/etc/nginx/nginx.conf:ro
  redis:
    image: redis:8.8-alpine@sha256:09160599abd229764c0fb44cb6be640294e1d360a54b19985ab4843dcf2d90f1
    restart: always
    ports:
      - "6379:6379"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack:4.14@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    ports:
      - "127.0.0.1:4566:4566"
      - "127.0.0.1:4510-4559:4510-4559"
    environment:
      - SERVICES=s3,kms
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      #- "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
