name: Golang-CI

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:

  preCommit:
    name: Run golang-ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.1
        with:
          version: latest
