name: terrafrom test

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: get terraform-version
        id: tf_ver
        run: echo "ver=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"

      - name: setup terrafrom
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.tf_ver.outputs.ver }}

      - name: Setup aws cli
        run: |
          mkdir ~/.aws
          chmod 700 ~/.aws
          echo "[profile localstack]" >> ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "endpoint_url = http://localhost:4566" >> ~/.aws/config
          echo "[localstack]" >> ~/.aws/credentials
          echo "aws_access_key_id = test" >> ~/.aws/credentials
          echo "aws_secret_access_key = test" >> ~/.aws/credentials
          # seems like the action ships with cli v1?
          sudo snap install aws-cli --classic
          aws --version

      # The default includes pipefile which breaks a few makefile things
      # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell
      - name: Run services
        shell: bash --noprofile --norc -x {0}
        env:
          AWS_PROFILE: localstack
        run: make run

      - name: Run test
        env:
          AWS_PROFILE: localstack
        run: make test
