name: terrafrom test

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7
      - name: Setup mise
        uses: jdx/mise-action@c2a87611a18de5b3828c5652fe268e992400cb5c  # v4.3.0
        with:
          version: 2026.9.5
          install: true

      - name: Setup aws cli
        run: |
          mkdir ~/.aws
          chmod 700 ~/.aws
          echo "[profile localstack]" >> ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "endpoint_url = http://localhost:4566" >> ~/.aws/config
          echo "[localstack]" >> ~/.aws/credentials
          echo "aws_access_key_id = test" >> ~/.aws/credentials
          echo "aws_secret_access_key = test" >> ~/.aws/credentials
          # seems like the action ships with cli v1?
          sudo snap install aws-cli --classic
          aws --version

      - name: Run services
        env:
          AWS_PROFILE: localstack
        run: make run

      - name: Run test
        env:
          AWS_PROFILE: localstack
        run: make test
