name: terrafrom test

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: setup go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: get terraform-version
        id: tf_ver
        run: echo "ver=$(cat .terraform-version)" >> "$GITHUB_OUTPUT"

      - name: setup terrafrom
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4
        with:
          terraform_version: ${{ steps.tf_ver.outputs.ver }}

      - name: Setup aws cli
        run: |
          mkdir ~/.aws
          chmod 700 ~/.aws
          echo "[profile localstack]" >> ~/.aws/config
          echo "region = us-east-2" >> ~/.aws/config
          echo "output = json" >> ~/.aws/config
          echo "endpoint_url = http://localhost:4566" >> ~/.aws/config
          echo "[localstack]" >> ~/.aws/credentials
          echo "aws_access_key_id = test" >> ~/.aws/credentials
          echo "aws_secret_access_key = test" >> ~/.aws/credentials
          # seems like the action ships with cli v1?
          sudo snap install aws-cli --classic
          aws --version

      - name: Run services
        env:
          AWS_PROFILE: localstack
        run: make run

      - name: Run test
        env:
          AWS_PROFILE: localstack
        run: make test
