name: terrafrom test

on:
  pull_request:
    branches:
      - main

permissions: read-all

jobs:
  terraform-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: "**/*.sum"

      - name: Setup aws cli
        run: |
          mkdir ~/.aws
          chmod 700 ~/.aws
          echo "[profile localstack]" >> ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config
          echo "output=json" >> ~/.aws/config
          echo "endpoint_url = http://localhost:4566" >> ~/.aws/config
          echo "[localstack]" >> ~/.aws/credentials
          echo "aws_access_key_id=test" >> ~/.aws/credentials
          echo "aws_secret_access_key=test" >> ~/.aws/credentials
          # seems like the action ships with cli v1?
          sudo snap install aws-cli --classic
          aws --version

      - name: Run services
        run: make run

      - name: Run test
        run: make test
